tests: Fix setting device I/O scheduler
Since Linux kernel version v6.5, the sysfs attribute "queue/scheduler"
is no longer available for bio based device-mapper targets. When
zonefs-tests.sh runs for such device, it fails to set up mq-deadline
as the device scheduler, which is required for zoned block devices.

To ensure that mq-deadline scheduler is applied during zonefs-tests.sh
run for bio based device-mapper targets, set mq-deadline scheduler for
the destination devices of the device-mapper device. If the sysfs
attribute "queue/scheduler" is not available, check if the test device
is a zoned device-mapper (linear, flakey or crypt). If so, get the
destination devices and set the I/O scheduler for these devices.

Signed-off-by: Shin'ichiro Kawasaki <shinichiro.kawasaki@wdc.com>
Signed-off-by: Damien Le Moal <dlemoal@kernel.org>

diff --git a/tests/scripts/test_lib b/tests/scripts/test_lib
--- a/tests/scripts/test_lib
+++ b/tests/scripts/test_lib
@@ -661,3 +661,84 @@ function max()
 
 	echo $((a > b ? a : b))
 }
+
+function get_dev_path_by_id()
+{
+	local d
+
+	for d in /sys/block/* /sys/block/*/*; do
+		if [[ ! -r "${d}/dev" ]]; then
+			continue
+		fi
+		if [[ "${1}" == "$(<"${d}/dev")" ]]; then
+			echo "/dev/${d##*/}"
+			return 0
+		fi
+	done
+	return 1
+}
+
+function set_dm_io_scheduler()
+{
+	local bdev="$1"
+	local sched="$2"
+	local dest_dev_id dest_dev path
+
+	while read -r dest_dev_id; do
+		if ! dest_dev=$(get_dev_path_by_id "${dest_dev_id}"); then
+			continue
+		fi
+		path=${dest_dev/dev/sys\/block}/queue/scheduler
+		if [[ ! -w ${path} ]]; then
+			echo "Can not set scheduler of device mapper destination: ${dest_dev}"
+			return 1
+		fi
+		echo "${sched}" > "${path}"
+	done < <(dmsetup table "$(<"/sys/block/$dev/dm/name")" |
+			 sed -n  's/.* \([0-9]*:[0-9]*\).*/\1/p')
+}
+
+function dev_has_dm_map()
+{
+	local dev=${1}
+	local target_type=${2}
+	local dm_name
+
+	[[ $(type -P "dmsetup") ]] ||
+		{
+			echo "dmsetup not found."
+			exit 1
+		}
+
+	dm_name=$(<"/sys/block/$dev/dm/name")
+	if ! dmsetup status "${dm_name}" | grep -qe "${target_type}"; then
+		return 1
+	fi
+
+	if dmsetup status "${dm_name}" | grep -v "${target_type}"; then
+		return 1
+	fi
+
+	return 0
+}
+
+function set_io_scheduler()
+{
+	local bdev="$1"
+	local sched="$2"
+
+	if [ -w "/sys/block/${bdev}/queue/scheduler" ]; then
+		echo "${sched}" > "/sys/block/${bdev}/queue/scheduler"
+		return 0
+	fi
+
+	if [ -r "/sys/block/$bdev/dm/name" ] &&
+		( dev_has_dm_map "$bdev" linear || dev_has_dm_map "$bdev" flakey ||
+		  dev_has_dm_map "$bdev" crypt ); then
+		set_dm_io_scheduler "${bdev}" "${sched}"
+	fi
+
+	echo "Failed to set I/O scheduler"
+	return 1
+}
+
